name: sicca
description: The Computational Food Composition System's or, the acronym in Portuguese, SiCCA's mobile application developed by Pedro Lacerda da Costa with Flutter & Dart for the members of the project to help them accomplish their tasks.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  injectable: ^1.5.3
  mockito: ^5.1.0
  recase: ^4.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.3
  freezed: ^1.1.1
  lint: ^1.8.2
  build_runner: ^2.1.8
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#f2f2f2"
  image: assets/icons/healthy-food-350.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/healthy-food-bg.png"
  image_path_android: "assets/icons/healthy-food-bg.png"
  adaptive_icon_background: "assets/icons/healthy-food-bg.png"
  adaptive_icon_foreground: "assets/icons/healthy-food-350.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  # fonts:
  #   - family: Death Star
  #     fonts:
  #       - asset: assets/fonts/.ttf